"""Fail-closed TVT result-macro release validator.

The standard runner deliberately leaves ``submission_unlocked`` false.  This
program is the only supported bridge from a runner-native ``run.json`` to
``paper/results_auto.tex``.  It writes nothing unless the formal source run,
all referenced artifacts, and a provenance-bound macro-value manifest pass.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from typing import Any
import zipfile


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RUNNER_PATH = PROJECT_ROOT / "experiments" / "run_standard_experiment.py"
FORMAL_DESIGNATION = "headline_formal_tvt_evidence"
MACRO_MANIFEST_SCHEMA = "vimd_amc.tvt.macro_values.v3"
RELEASE_LOCK_SCHEMA = "vimd_amc.tvt.release_lock.v2"
RELEASE_SENTINEL = "EligibleLockedResults"
RELEASE_SENTINEL_VALUE = "eligible_locked_formal_run"
SUMMARY_RESULT_MACROS = (
    "PrimaryReference",
    "StrongestBaseline",
    "HardMacroFOneGain",
    "HardMacroFOneCI",
    "HeldoutJammerGain",
    "HeldoutChannelGain",
    "FeatureSIRGain",
    "VIMDParameters",
    "VIMDLatency",
)
HEADLINE_MODEL_TOKENS = ("Direct", "MCLDNN", "IQFormer", "CSSL", "VIMD")
HEADLINE_METRIC_TOKENS = (
    "Accuracy",
    "MacroFOne",
    "WorstRecall",
    "NLL",
    "ECE",
)
HEADLINE_RESULT_MACROS = tuple(
    f"Headline{model}{metric}"
    for model in HEADLINE_MODEL_TOKENS
    for metric in HEADLINE_METRIC_TOKENS
)
OOD_REGIME_TOKENS = (
    "Hard",
    "UnseenJammer",
    "UnseenSpeed",
    "HeldoutChannel",
    "CombinedOOD",
    "CleanSeen",
    "CleanHeldout",
)
OOD_RESULT_MACROS = tuple(
    f"OOD{regime}{field}"
    for regime in OOD_REGIME_TOKENS
    for field in ("ReferenceFOne", "VIMDFOne", "GainCI")
)
MECHANISM_RESULT_MACROS = (
    "MechanismMaskJS",
    "MechanismOverlapWeightedCorrelation",
    "MechanismOverlapSpearman",
    "MechanismTargetTransfer",
    "MechanismAmplificationShare",
    "MechanismJammerLeakage",
    "MechanismOverlapPermutationP",
)
RESULT_MACROS = (
    *SUMMARY_RESULT_MACROS,
    *HEADLINE_RESULT_MACROS,
    *OOD_RESULT_MACROS,
    *MECHANISM_RESULT_MACROS,
)
ALL_MACROS = (RELEASE_SENTINEL, "ResultSource", *RESULT_MACROS)
RESULTS_AUTO_COMMENTS = (
    "% AUTO-GENERATED by tvt_submission/validate_release.py.",
    "% Do not edit reported values by hand; release_lock.json binds source.",
)
RELEASE_LOCK_KEYS = frozenset(
    {
        "schema_version",
        "submission_unlocked",
        "generated_utc",
        "run_id",
        "cache_digest",
        "formal_cache_designation",
        "release_sentinel_name",
        "release_sentinel_value",
        "run_json_sha256",
        "results_auto_sha256",
        "macro_value_manifest_sha256",
        "source_gate_sha256",
        "artifact_audit",
        "macro_provenance",
    }
)
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
PLACEHOLDER_TERMS = (
    "pending",
    "generated",
    "placeholder",
    "tbd",
    "todo",
    "unavailable",
    "n/a",
    "nan",
    "no eligible locked run",
    "internal review",
)
DANGEROUS_TEX = re.compile(
    r"\\(?:input|include|write|openout|read|catcode|csname|newcommand|"
    r"renewcommand|providecommand|def|gdef|edef|xdef|usepackage|"
    r"documentclass|begin|end|loop|repeat|par)\b",
    flags=re.IGNORECASE,
)
MACRO_LINE = re.compile(
    r"^\s*\\newcommand\{\\(?P<name>[A-Za-z][A-Za-z0-9]*)\}"
    r"\{(?P<value>.*)\}\s*$"
)


class ReleaseValidationError(RuntimeError):
    """A release invariant failed; callers must not write submission files."""


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key!r}")
        result[key] = value
    return result


def _reject_nonstandard_constant(value: str) -> None:
    raise ValueError(f"non-standard JSON constant: {value}")


def load_strict_json(path: Path) -> dict[str, Any]:
    try:
        with path.open(encoding="utf-8") as stream:
            payload = json.load(
                stream,
                object_pairs_hook=_strict_object,
                parse_constant=_reject_nonstandard_constant,
            )
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        raise ReleaseValidationError(
            f"strict JSON load failed for {path}: {error}"
        ) from error
    if not isinstance(payload, dict):
        raise ReleaseValidationError(f"JSON root is not an object: {path}")
    return payload


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _canonical_digest(payload: dict[str, Any]) -> str:
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _load_runner_module() -> Any:
    specification = importlib.util.spec_from_file_location(
        "vimd_release_runner_contract",
        RUNNER_PATH,
    )
    if specification is None or specification.loader is None:
        raise ReleaseValidationError("could not load the standard runner")
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    try:
        specification.loader.exec_module(module)
    except Exception as error:
        raise ReleaseValidationError(
            f"could not import the standard runner: {error}"
        ) from error
    return module


def _safe_run_relative(run_root: Path, value: Any, label: str) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise ReleaseValidationError(f"{label} is missing or not a path")
    relative = Path(value)
    if relative.is_absolute():
        raise ReleaseValidationError(f"{label} must be run-relative: {value}")
    candidate = (run_root / relative).resolve()
    try:
        candidate.relative_to(run_root.resolve())
    except ValueError as error:
        raise ReleaseValidationError(
            f"{label} escapes the run directory: {value}"
        ) from error
    return candidate


def _require_nonempty_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise ReleaseValidationError(f"{label} is absent: {path}")
    if path.stat().st_size <= 0:
        raise ReleaseValidationError(f"{label} is empty: {path}")


def _artifact_audit(
    run_json: Path,
    run_record: dict[str, Any],
) -> dict[str, Any]:
    run_root = run_json.parent.resolve()
    required_paths: set[Path] = {
        run_root / "metrics.csv",
        run_root / "paired_statistics.csv",
        run_root / "headline_paired_statistics.csv",
        run_root / "manifests" / "cache_reference.json",
    }
    splits = run_record.get("splits")
    if not isinstance(splits, dict) or not splits:
        raise ReleaseValidationError("run split contract is missing")
    evaluation_splits = sorted(
        str(split) for split in splits if str(split) != "train"
    )
    if not evaluation_splits:
        raise ReleaseValidationError("run has no evaluation splits")
    for split in splits:
        required_paths.add(
            run_root / "manifests" / f"{str(split)}.json"
        )
    seeds = run_record.get("seeds")
    if isinstance(seeds, list) and len(seeds) > 1:
        required_paths.add(run_root / "seed_aggregates.csv")

    statistics = run_record.get("statistical_outputs")
    if not isinstance(statistics, dict):
        raise ReleaseValidationError("statistical_outputs is malformed")
    for key in ("single_seed_pairs", "multi_seed_headline_pairs"):
        required_paths.add(
            _safe_run_relative(
                run_root,
                statistics.get(key),
                f"statistical_outputs.{key}",
            )
        )

    results = run_record.get("results")
    if not isinstance(results, list):
        raise ReleaseValidationError("run results are malformed")
    expected_pairs = {
        (str(model), int(seed))
        for model in run_record.get("models", [])
        for seed in run_record.get("seeds", [])
    }
    observed_pairs: set[tuple[str, int]] = set()
    for index, result in enumerate(results):
        if not isinstance(result, dict):
            raise ReleaseValidationError(
                f"result index {index} is not an object"
            )
        try:
            model = str(result["model"])
            seed = int(result["seed"])
        except (KeyError, TypeError, ValueError, OverflowError) as error:
            raise ReleaseValidationError(
                f"result index {index} has invalid model/seed"
            ) from error
        pair = (model, seed)
        if pair in observed_pairs:
            raise ReleaseValidationError(
                f"duplicate result for {model}/seed{seed}"
            )
        observed_pairs.add(pair)
        model_root = run_root / "models" / f"{model}_seed{seed}"
        result_path = model_root / "result.json"
        required_paths.add(result_path)
        checkpoint = _safe_run_relative(
            run_root,
            result.get("checkpoint"),
            f"{model}/seed{seed} checkpoint",
        )
        required_paths.add(checkpoint)
        teacher_checkpoint = result.get("teacher_checkpoint")
        if teacher_checkpoint is not None:
            required_paths.add(
                _safe_run_relative(
                    run_root,
                    teacher_checkpoint,
                    f"{model}/seed{seed} teacher checkpoint",
                )
            )
        regimes = result.get("regimes")
        if not isinstance(regimes, dict) or set(regimes) != set(
            evaluation_splits
        ):
            raise ReleaseValidationError(
                f"{model}/seed{seed} evaluation regime set is incomplete"
            )
        for split in evaluation_splits:
            required_paths.add(
                model_root / f"predictions_{split}.npz"
            )

    if observed_pairs != expected_pairs:
        missing = sorted(expected_pairs.difference(observed_pairs))
        unexpected = sorted(observed_pairs.difference(expected_pairs))
        raise ReleaseValidationError(
            f"model/seed artifact matrix mismatch; missing={missing}, "
            f"unexpected={unexpected}"
        )

    for path in sorted(required_paths):
        _require_nonempty_file(path, "required run artifact")
        if path.suffix == ".npz" and not zipfile.is_zipfile(path):
            raise ReleaseValidationError(f"invalid NPZ artifact: {path}")

    for model, seed in sorted(observed_pairs):
        expected_result = next(
            item
            for item in results
            if item.get("model") == model and int(item.get("seed")) == seed
        )
        result_path = (
            run_root / "models" / f"{model}_seed{seed}" / "result.json"
        )
        if load_strict_json(result_path) != expected_result:
            raise ReleaseValidationError(
                f"result.json disagrees with run.json for {model}/seed{seed}"
            )

    cache_root_value = run_record.get("cache_root")
    if not isinstance(cache_root_value, str) or not cache_root_value:
        raise ReleaseValidationError("cache_root is missing")
    cache_manifest_path = Path(cache_root_value).expanduser().resolve()
    cache_manifest_path = cache_manifest_path / "manifest.json"
    _require_nonempty_file(cache_manifest_path, "formal cache manifest")
    cache_manifest = load_strict_json(cache_manifest_path)
    if cache_manifest.get("cache_digest") != run_record.get("cache_digest"):
        raise ReleaseValidationError(
            "formal cache manifest digest disagrees with run.json"
        )
    configuration = cache_manifest.get("configuration")
    if (
        not isinstance(configuration, dict)
        or configuration.get("evidence_designation") != FORMAL_DESIGNATION
    ):
        raise ReleaseValidationError(
            "formal cache manifest designation is not the frozen headline "
            "designation"
        )

    return {
        "passed": True,
        "required_artifact_count": len(required_paths),
        "evaluation_splits": evaluation_splits,
        "model_seed_pairs": [
            {"model": model, "seed": seed}
            for model, seed in sorted(observed_pairs)
        ],
        "cache_manifest": str(cache_manifest_path),
    }


def validate_source_run(
    run_json: Path,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    resolved = run_json.expanduser().resolve()
    _require_nonempty_file(resolved, "run.json")
    run_record = load_strict_json(resolved)
    if run_record.get("runner") != "experiments/run_standard_experiment.py":
        raise ReleaseValidationError("run.json is not runner-native")
    if run_record.get("checksums_verified") is not True:
        raise ReleaseValidationError("cache checksums were not verified")
    eligibility = run_record.get("evidence_eligibility")
    if not isinstance(eligibility, dict):
        raise ReleaseValidationError("evidence_eligibility is malformed")
    if eligibility.get("cache_designation") != FORMAL_DESIGNATION:
        raise ReleaseValidationError(
            "screening, alias, or missing cache designation cannot unlock TVT"
        )
    if eligibility.get("policy_version") != "vimd-evidence-gate-v2":
        raise ReleaseValidationError(
            "run does not use the current evidence-gate policy"
        )

    runner = _load_runner_module()
    computed_gate = runner.submission_release_source_gate(run_record)
    if computed_gate.get("macro_generation_permitted") is not True:
        raise ReleaseValidationError(
            "source-run release gate rejected the run: "
            + "; ".join(str(item) for item in computed_gate.get("reasons", []))
        )
    serialized_gate = run_record.get("submission_release")
    if (
        not isinstance(serialized_gate, dict)
        or serialized_gate.get("macro_generation_permitted") is not True
        or serialized_gate.get("reasons") != []
    ):
        raise ReleaseValidationError(
            "serialized submission_release does not explicitly permit macros"
        )
    if serialized_gate.get("submission_unlocked") is not False:
        raise ReleaseValidationError(
            "runner-native run must remain locked until this validator runs"
        )
    artifact_audit = _artifact_audit(resolved, run_record)
    return run_record, computed_gate, artifact_audit


def _is_placeholder(value: str) -> bool:
    normalized = " ".join(value.strip().casefold().split())
    if normalized in {"", "-", "--", "—", "–", "none", "null"}:
        return True
    return any(term in normalized for term in PLACEHOLDER_TERMS)


def _validate_tex_value(name: str, value: Any) -> str:
    if not isinstance(value, str):
        raise ReleaseValidationError(f"macro {name} value is not a string")
    if len(value) > 500:
        raise ReleaseValidationError(f"macro {name} value is too long")
    if "\n" in value or "\r" in value or "\x00" in value:
        raise ReleaseValidationError(
            f"macro {name} contains a line break or NUL"
        )
    if _is_placeholder(value):
        raise ReleaseValidationError(
            f"macro {name} is empty or contains a placeholder"
        )
    if DANGEROUS_TEX.search(value) or "#" in value:
        raise ReleaseValidationError(
            f"macro {name} contains prohibited TeX control content"
        )
    if re.search(r"(?<!\\)%", value):
        raise ReleaseValidationError(
            f"macro {name} contains an unescaped percent sign"
        )
    depth = 0
    for character in value:
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
        if depth < 0:
            break
    if depth != 0:
        raise ReleaseValidationError(
            f"macro {name} has unbalanced braces"
        )
    return value.strip()


def validate_macro_manifest(
    path: Path,
    *,
    run_json: Path,
    run_record: dict[str, Any],
) -> tuple[dict[str, str], dict[str, dict[str, str]]]:
    manifest = load_strict_json(path.expanduser().resolve())
    if manifest.get("schema_version") != MACRO_MANIFEST_SCHEMA:
        raise ReleaseValidationError("macro-value manifest schema mismatch")
    if manifest.get("run_id") != run_record.get("run_id"):
        raise ReleaseValidationError("macro-value manifest run_id mismatch")
    if manifest.get("cache_digest") != run_record.get("cache_digest"):
        raise ReleaseValidationError(
            "macro-value manifest cache_digest mismatch"
        )
    if manifest.get("run_json_sha256") != sha256_file(run_json.resolve()):
        raise ReleaseValidationError(
            "macro-value manifest is not bound to the exact run.json"
        )
    records = manifest.get("macros")
    if not isinstance(records, dict) or set(records) != set(RESULT_MACROS):
        raise ReleaseValidationError(
            "macro-value manifest must contain exactly the required macros"
        )

    values: dict[str, str] = {}
    provenance: dict[str, dict[str, str]] = {}
    run_root = run_json.resolve().parent
    for name in RESULT_MACROS:
        record = records.get(name)
        if not isinstance(record, dict):
            raise ReleaseValidationError(
                f"macro {name} record is not an object"
            )
        if set(record) != {"value", "source_artifact", "derivation"}:
            raise ReleaseValidationError(
                f"macro {name} record must have value, source_artifact, "
                "and derivation only"
            )
        value = _validate_tex_value(name, record["value"])
        source_path = _safe_run_relative(
            run_root,
            record["source_artifact"],
            f"macro {name} source_artifact",
        )
        _require_nonempty_file(source_path, f"macro {name} source artifact")
        derivation = record["derivation"]
        if (
            not isinstance(derivation, str)
            or len(derivation.strip()) < 12
            or _is_placeholder(derivation)
            or "\n" in derivation
            or "\r" in derivation
        ):
            raise ReleaseValidationError(
                f"macro {name} derivation is missing or non-auditable"
            )
        values[name] = value
        provenance[name] = {
            "source_artifact": str(
                source_path.relative_to(run_root).as_posix()
            ),
            "source_sha256": sha256_file(source_path),
            "derivation": derivation.strip(),
        }
    return values, provenance


def canonical_macro_manifest_text(manifest: dict[str, Any]) -> str:
    """Return the only byte representation accepted by the release writer."""

    return (
        json.dumps(
            manifest,
            ensure_ascii=False,
            allow_nan=False,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def rebuild_expected_macro_manifest(run_json: Path) -> dict[str, Any]:
    """Re-derive every macro from immutable run artifacts.

    The import is deliberately lazy because ``generate_macro_values`` uses
    this module's source-run and manifest validators.  Keeping derivation in
    that module avoids a second, weaker implementation in the release writer.
    """

    try:
        from tvt_submission import generate_macro_values

        return generate_macro_values.generate_macro_manifest(
            run_json.expanduser().resolve()
        )
    except Exception as error:
        raise ReleaseValidationError(
            f"could not rebuild the expected macro manifest: {error}"
        ) from error


def validate_expected_macro_manifest(
    path: Path,
    *,
    run_json: Path,
) -> dict[str, Any]:
    """Require the supplied manifest to equal deterministic re-derivation."""

    resolved = path.expanduser().resolve()
    supplied = load_strict_json(resolved)
    expected = rebuild_expected_macro_manifest(run_json)
    if supplied != expected:
        raise ReleaseValidationError(
            "macro-value manifest differs from deterministic artifact "
            "re-derivation; manually supplied values, units, sources, or "
            "derivations are prohibited"
        )
    expected_text = canonical_macro_manifest_text(expected)
    try:
        supplied_text = resolved.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ReleaseValidationError(
            f"could not read macro-value manifest bytes: {error}"
        ) from error
    if supplied_text != expected_text:
        raise ReleaseValidationError(
            "macro-value manifest bytes are not the canonical generator "
            "serialization"
        )
    return expected


def _require_sha256(value: Any, label: str) -> str:
    if not isinstance(value, str) or SHA256_PATTERN.fullmatch(value) is None:
        raise ReleaseValidationError(f"{label} is not a lowercase SHA-256")
    return value


def validate_release_lock_structure(
    lock: dict[str, Any],
    *,
    results_auto_sha256: str | None = None,
) -> None:
    """Validate the portable schema-v2 portion of a release lock.

    Full source-run validation remains the responsibility of
    :func:`validate_existing_release`; this helper is also safe for the
    read-only paper-build gate, which may not have the run directory.
    """

    if set(lock) != RELEASE_LOCK_KEYS:
        missing = sorted(RELEASE_LOCK_KEYS.difference(lock))
        unexpected = sorted(set(lock).difference(RELEASE_LOCK_KEYS))
        raise ReleaseValidationError(
            "release lock keys mismatch; "
            f"missing={missing}, unexpected={unexpected}"
        )
    if lock.get("schema_version") != RELEASE_LOCK_SCHEMA:
        raise ReleaseValidationError("release lock schema mismatch")
    if lock.get("submission_unlocked") is not True:
        raise ReleaseValidationError("release lock is not explicitly unlocked")
    if lock.get("formal_cache_designation") != FORMAL_DESIGNATION:
        raise ReleaseValidationError("release lock formal designation mismatch")
    if lock.get("release_sentinel_name") != RELEASE_SENTINEL:
        raise ReleaseValidationError("release lock sentinel name mismatch")
    if lock.get("release_sentinel_value") != RELEASE_SENTINEL_VALUE:
        raise ReleaseValidationError("release lock sentinel value mismatch")
    for key in (
        "run_json_sha256",
        "results_auto_sha256",
        "macro_value_manifest_sha256",
        "source_gate_sha256",
    ):
        _require_sha256(lock.get(key), f"release lock {key}")
    _require_sha256(lock.get("cache_digest"), "release lock cache_digest")
    if results_auto_sha256 is not None:
        expected_digest = _require_sha256(
            results_auto_sha256,
            "expected results_auto_sha256",
        )
        if lock.get("results_auto_sha256") != expected_digest:
            raise ReleaseValidationError(
                "release lock is not bound to the exact results_auto.tex"
            )
    if not isinstance(lock.get("run_id"), str) or not lock["run_id"].strip():
        raise ReleaseValidationError("release lock run_id is missing")
    generated = lock.get("generated_utc")
    if not isinstance(generated, str):
        raise ReleaseValidationError("release lock generated_utc is missing")
    try:
        parsed_time = datetime.fromisoformat(generated)
    except ValueError as error:
        raise ReleaseValidationError(
            "release lock generated_utc is not ISO-8601"
        ) from error
    if parsed_time.tzinfo is None:
        raise ReleaseValidationError(
            "release lock generated_utc must include a timezone"
        )
    artifact_audit = lock.get("artifact_audit")
    if (
        not isinstance(artifact_audit, dict)
        or artifact_audit.get("passed") is not True
    ):
        raise ReleaseValidationError("release lock artifact audit is malformed")
    provenance = lock.get("macro_provenance")
    if not isinstance(provenance, dict) or set(provenance) != set(
        RESULT_MACROS
    ):
        raise ReleaseValidationError("release lock macro provenance is incomplete")
    for name, record in provenance.items():
        if not isinstance(record, dict) or set(record) != {
            "source_artifact",
            "source_sha256",
            "derivation",
        }:
            raise ReleaseValidationError(
                f"release lock provenance is malformed for {name}"
            )
        if (
            not isinstance(record["source_artifact"], str)
            or not record["source_artifact"].strip()
            or not isinstance(record["derivation"], str)
            or len(record["derivation"].strip()) < 12
        ):
            raise ReleaseValidationError(
                f"release lock provenance is incomplete for {name}"
            )
        _require_sha256(
            record["source_sha256"],
            f"release lock {name} source_sha256",
        )


def _escape_metadata(value: Any) -> str:
    text = str(value)
    for source, replacement in (
        ("\\", r"\textbackslash{}"),
        ("_", r"\_"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("&", r"\&"),
        ("{", r"\{"),
        ("}", r"\}"),
    ):
        text = text.replace(source, replacement)
    return text


def render_results_auto(
    run_record: dict[str, Any],
    values: dict[str, str],
) -> str:
    run_id = _escape_metadata(run_record["run_id"])
    cache_digest = _escape_metadata(str(run_record["cache_digest"])[:16])
    result_source = (
        f"locked formal run \\texttt{{{run_id}}}, cache "
        f"\\texttt{{{cache_digest}}}"
    )
    lines = [
        *RESULTS_AUTO_COMMENTS,
        (
            rf"\newcommand{{\{RELEASE_SENTINEL}}}"
            rf"{{{RELEASE_SENTINEL_VALUE}}}"
        ),
        rf"\newcommand{{\ResultSource}}{{{result_source}}}",
    ]
    lines.extend(
        rf"\newcommand{{\{name}}}{{{values[name]}}}"
        for name in RESULT_MACROS
    )
    return "\n".join(lines) + "\n"


def parse_results_auto(path: Path) -> dict[str, str]:
    _require_nonempty_file(path, "paper result macro file")
    parsed: dict[str, str] = {}
    observed_comments: list[str] = []
    for line_number, line in enumerate(
        path.read_text(encoding="utf-8").splitlines(),
        start=1,
    ):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("%"):
            if stripped not in RESULTS_AUTO_COMMENTS:
                raise ReleaseValidationError(
                    "paper result macro file contains an unapproved comment "
                    f"at line {line_number}"
                )
            observed_comments.append(stripped)
            continue
        match = MACRO_LINE.match(line)
        if match is None:
            raise ReleaseValidationError(
                "paper result macro file contains executable or unknown "
                f"content at line {line_number}"
            )
        name = match.group("name")
        if name not in ALL_MACROS:
            raise ReleaseValidationError(
                "paper result macro file defines an unexpected macro at "
                f"line {line_number}: {name}"
            )
        if name in parsed:
            raise ReleaseValidationError(
                f"duplicate macro definition in {path}: {name}"
            )
        parsed[name] = match.group("value")
    if tuple(observed_comments) != RESULTS_AUTO_COMMENTS:
        raise ReleaseValidationError(
            "paper result macro file is missing or reorders the controlled "
            "auto-generated comments"
        )
    missing = sorted(set(ALL_MACROS).difference(parsed))
    if missing:
        raise ReleaseValidationError(
            "paper result macro file is incomplete: " + ",".join(missing)
        )
    if parsed[RELEASE_SENTINEL] != RELEASE_SENTINEL_VALUE:
        raise ReleaseValidationError(
            "paper result macro file has an invalid eligible-release sentinel"
        )
    for name in ALL_MACROS:
        _validate_tex_value(name, parsed[name])
    return parsed


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _paper_paths(paper_root: Path) -> tuple[Path, Path]:
    root = paper_root.expanduser().resolve()
    if not (root / "main.tex").is_file():
        raise ReleaseValidationError(
            f"paper root does not contain main.tex: {root}"
        )
    return root / "results_auto.tex", root / "release_lock.json"


def write_release(
    *,
    run_json: Path,
    paper_root: Path,
    macro_values: Path,
    replace_existing_release: bool = False,
) -> dict[str, Any]:
    resolved_run_json = run_json.expanduser().resolve()
    run_record, source_gate, artifact_audit = validate_source_run(
        resolved_run_json
    )
    values, provenance = validate_macro_manifest(
        macro_values,
        run_json=resolved_run_json,
        run_record=run_record,
    )
    expected_manifest = validate_expected_macro_manifest(
        macro_values,
        run_json=resolved_run_json,
    )
    results_path, lock_path = _paper_paths(paper_root)
    if lock_path.exists() and not replace_existing_release:
        raise ReleaseValidationError(
            "release_lock.json already exists; pass "
            "--replace-existing-release for an intentional replacement"
        )
    rendered = render_results_auto(run_record, values)
    rendered_digest = hashlib.sha256(rendered.encode("utf-8")).hexdigest()
    lock = {
        "schema_version": RELEASE_LOCK_SCHEMA,
        "submission_unlocked": True,
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "run_id": run_record["run_id"],
        "cache_digest": run_record["cache_digest"],
        "formal_cache_designation": FORMAL_DESIGNATION,
        "release_sentinel_name": RELEASE_SENTINEL,
        "release_sentinel_value": RELEASE_SENTINEL_VALUE,
        "run_json_sha256": sha256_file(resolved_run_json),
        "results_auto_sha256": rendered_digest,
        "macro_value_manifest_sha256": hashlib.sha256(
            canonical_macro_manifest_text(expected_manifest).encode("utf-8")
        ).hexdigest(),
        "source_gate_sha256": _canonical_digest(source_gate),
        "artifact_audit": artifact_audit,
        "macro_provenance": provenance,
    }
    lock_text = json.dumps(
        lock,
        ensure_ascii=False,
        allow_nan=False,
        indent=2,
        sort_keys=True,
    ) + "\n"
    validate_release_lock_structure(
        lock,
        results_auto_sha256=rendered_digest,
    )
    # Publish the lock first.  If the second atomic replacement fails, the
    # lock/hash mismatch keeps the old macro file closed.  Publishing macros
    # first could leave new submission values visible without any lock.
    _atomic_write_text(lock_path, lock_text)
    _atomic_write_text(results_path, rendered)
    return {
        "ok": True,
        "action": "release_written",
        "submission_unlocked": True,
        "run_id": run_record["run_id"],
        "results_auto": str(results_path),
        "release_lock": str(lock_path),
        "results_auto_sha256": rendered_digest,
    }


def validate_existing_release(
    *,
    run_json: Path,
    paper_root: Path,
) -> dict[str, Any]:
    resolved_run_json = run_json.expanduser().resolve()
    run_record, source_gate, _ = validate_source_run(resolved_run_json)
    results_path, lock_path = _paper_paths(paper_root)
    parsed_results = parse_results_auto(results_path)
    lock = load_strict_json(lock_path)
    validate_release_lock_structure(
        lock,
        results_auto_sha256=sha256_file(results_path),
    )
    expected_manifest = rebuild_expected_macro_manifest(resolved_run_json)
    expected_values = {
        name: str(expected_manifest["macros"][name]["value"])
        for name in RESULT_MACROS
    }
    expected_results = render_results_auto(run_record, expected_values)
    try:
        actual_results = results_path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ReleaseValidationError(
            f"could not read paper result macro file: {error}"
        ) from error
    if actual_results != expected_results:
        raise ReleaseValidationError(
            "paper result macro file differs from deterministic artifact "
            "re-derivation"
        )
    if any(
        parsed_results[name] != expected_values[name]
        for name in RESULT_MACROS
    ):
        raise ReleaseValidationError(
            "paper result macro values differ from deterministic artifact "
            "re-derivation"
        )
    expected_manifest_digest = hashlib.sha256(
        canonical_macro_manifest_text(expected_manifest).encode("utf-8")
    ).hexdigest()
    if lock.get("macro_value_manifest_sha256") != expected_manifest_digest:
        raise ReleaseValidationError(
            "release lock macro manifest digest disagrees with deterministic "
            "artifact re-derivation"
        )
    expected = {
        "schema_version": RELEASE_LOCK_SCHEMA,
        "submission_unlocked": True,
        "run_id": run_record.get("run_id"),
        "cache_digest": run_record.get("cache_digest"),
        "formal_cache_designation": FORMAL_DESIGNATION,
        "release_sentinel_name": RELEASE_SENTINEL,
        "release_sentinel_value": RELEASE_SENTINEL_VALUE,
        "run_json_sha256": sha256_file(resolved_run_json),
        "results_auto_sha256": sha256_file(results_path),
        "source_gate_sha256": _canonical_digest(source_gate),
    }
    mismatches = [
        key for key, value in expected.items() if lock.get(key) != value
    ]
    if mismatches:
        raise ReleaseValidationError(
            "release lock mismatch: " + ",".join(sorted(mismatches))
        )
    provenance = lock.get("macro_provenance")
    expected_provenance = {
        name: {
            "source_artifact": str(
                expected_manifest["macros"][name]["source_artifact"]
            ),
            "source_sha256": sha256_file(
                _safe_run_relative(
                    resolved_run_json.parent,
                    expected_manifest["macros"][name]["source_artifact"],
                    f"expected macro {name} source",
                )
            ),
            "derivation": str(
                expected_manifest["macros"][name]["derivation"]
            ).strip(),
        }
        for name in RESULT_MACROS
    }
    if provenance != expected_provenance:
        raise ReleaseValidationError(
            "release lock provenance differs from deterministic artifact "
            "re-derivation"
        )
    run_root = resolved_run_json.parent
    for name, record in provenance.items():
        if not isinstance(record, dict):
            raise ReleaseValidationError(
                f"release lock provenance is malformed for {name}"
            )
        source_path = _safe_run_relative(
            run_root,
            record.get("source_artifact"),
            f"release lock {name} source",
        )
        _require_nonempty_file(source_path, f"release lock {name} source")
        if record.get("source_sha256") != sha256_file(source_path):
            raise ReleaseValidationError(
                f"macro source artifact changed after release: {name}"
            )
    return {
        "ok": True,
        "action": "existing_release_validated",
        "submission_unlocked": True,
        "run_id": run_record["run_id"],
        "results_auto": str(results_path),
        "release_lock": str(lock_path),
    }


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-json", required=True, type=Path)
    parser.add_argument("--paper-root", required=True, type=Path)
    parser.add_argument("--macro-values", type=Path)
    parser.add_argument(
        "--write",
        action="store_true",
        help="atomically write results_auto.tex and release_lock.json",
    )
    parser.add_argument(
        "--replace-existing-release",
        action="store_true",
        help="allow intentional replacement of an existing release lock",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_argument_parser().parse_args(argv)
    try:
        if arguments.write:
            if arguments.macro_values is None:
                raise ReleaseValidationError(
                    "--write requires --macro-values"
                )
            result = write_release(
                run_json=arguments.run_json,
                paper_root=arguments.paper_root,
                macro_values=arguments.macro_values,
                replace_existing_release=arguments.replace_existing_release,
            )
        elif arguments.macro_values is not None:
            run_record, _, artifact_audit = validate_source_run(
                arguments.run_json
            )
            values, provenance = validate_macro_manifest(
                arguments.macro_values,
                run_json=arguments.run_json.expanduser().resolve(),
                run_record=run_record,
            )
            result = {
                "ok": True,
                "action": "preflight_only_no_files_written",
                "submission_unlocked": False,
                "macro_count": len(values),
                "provenance_count": len(provenance),
                "artifact_audit": artifact_audit,
            }
        else:
            result = validate_existing_release(
                run_json=arguments.run_json,
                paper_root=arguments.paper_root,
            )
    except ReleaseValidationError as error:
        print(
            json.dumps(
                {
                    "ok": False,
                    "submission_unlocked": False,
                    "error": str(error),
                },
                ensure_ascii=False,
                allow_nan=False,
                sort_keys=True,
            ),
            file=sys.stderr,
        )
        return 2
    print(
        json.dumps(
            result,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
